Repository Spotifyd/spotifyd, pull requests merged in 2023-03, with the labels that each got.

#1187 add CNAME to gh-pages
  .github/workflows/docs.yml
Labels: ci

#1183 Update dependencies, except librespot
  Cargo.lock
  Cargo.toml
Labels: dependencies

#1182 Librespot upgrade to 0.4
  Cargo.lock
  Cargo.toml
  src/alsa_mixer.rs
  src/config.rs
  src/dbus_mpris.rs
  src/main_loop.rs
  src/no_mixer.rs
  src/process.rs
  src/setup.rs
Labels: dependencies

#1082 feat: option for audio format
  docs/src/config/File.md
  src/config.rs
  src/main_loop.rs
  src/setup.rs
Labels: enhancement
